name: Setup Helm
description: A GitHub Action for running Helm commands
author: Stefan Prodan
branding:
  color: blue
  icon: command
inputs:
  version:
    description: "Helm version"
    required: true
runs:
  using: composite
  steps:
    - name: "Install Helm"
      shell: bash
      run: |
        VERSION=${{ inputs.version }}
        cd /tmp
        curl -sL https://get.helm.sh/helm-v${VERSION}-linux-amd64.tar.gz | tar xz
        sudo cp ./linux-amd64/helm /usr/local/bin
    - name: "Verify correct installation of binary"
      shell: bash
      run: |
        helm version
